#已创建订单的在全局字典中的键,用于删除

shipment_demand_key:  #运输下单
  - cn_rail_order_id
  - submit_cn_rail_order_id
  - cn_rail_save_id
  - cn_sea_save_id
  - submit_cn_sea_order_id
  - cn_sea_order_id
  - cn_air_save_id
  - submit_cn_air_order_id
  - cn_air_order_id
  - cn_road_save_id
  - submit_cn_road_order_id
  - road_order_id
  - cn_express_save_id
  - submit_cn_express_order_id
  - express_order_id
  - internat_sea_save_id
  - submit_internat_sea_order_id
  - internat_sea_order_id
  - internat_air_save_id
  - submit_internat_air_order_id
  - inernat_air_order_id
  - international_express_save_id
  - submit_internat_express_order_id
  - internat_express_order_id
  - copy_order_id
  - success_create_road_receiving_order_id

middle_data_key:    #中台的收发货方
  contacts_key:
    - shpper_id
    - internat_shpper_id
  contacts_addr_key:
    - shpper_addr_id
    - internat_shpper_addr_id