# 读取excel文件及sheet名称


file_name:
  -
    excel_name: 运输下单测试用例-DEV.xlsx
    sheet_name:
      -  登录
      -  基础数据
#      -  国内铁运
#      -  国内陆运
#      -  国内海运
#      -  国内空运
#      -  国际海运
#      -  国际空运
      -  运输需求
#      -  国际确认下单

  -
    excel_name: 运输下单测试用例-SIT.xlsx
    sheet_name:
      -  登录
      -  基础数据
      -  国内铁运
      -  国内陆运
      -  国内海运
      -  国内空运
      -  国际海运
      -  国际空运
      -  运输需求
#      -  国际确认下单


  -
    excel_name: 运输下单测试用例-UAT.xlsx
    sheet_name:
      - 登录
      - 基础数据
      - 国际海运
      -  国际空运
      -  国内铁运
      -  国内陆运
      -  国内海运
      -  国内空运
      -  运输需求
      -  国际确认下单